### ISSUE TITLE
Flaky test: TestTailFuzz

### ISSUE THREAD

**Issue by jkohen** [Stackdriver/stackdriver-prometheus-sidecar#67] opened 2018-12-07 23:50 UTC
This test failed during presubmit, and it's unrelated to my PR (which was documentation only): https://travis-ci.com/Stackdriver/stackdriver-prometheus-sidecar/builds/94064905

@fabxc how can we investigate this?

**Comment by fabxc** [comment] 2018-12-11 12:44
The tailer keeps retrying to read more data until its context get canceled. Currently the test waits a fixed amount of time until it cancels after writing the last record. My guess is that the tailer just hasn't read everything yet before the writing goroutine terminates it.

I tried to reproduce this by running the test at high parallelism to cause contention but could not reproduce it.
Possibly the process gets completely stalled for longer on Travis. I'd probably just raise the timeout for now. While it's not a 'proper' fix, anything that coordinates explicitly between reader and writer would seem to kill the fuzz part of the test a bit.

**Comment by jkohen** [comment] 2019-08-02 20:04
Reopening. I only fixed one issue. We're also seeing `panic: write /tmp/test_tail370907351/00000059: file already closed`, which already existed before this change.

**Comment by qingling128** [comment] 2024-08-12 16:25
Closing this issue as the component has been deprecated.

**Closed by qingling128** 2024-08-12 16:25 UTC
Labels: cleanup
